### ISSUE TITLE
Difference between ncounts, read count, and UMI count

### ISSUE THREAD

**Issue by zhan8855** [sanderlab/scPerturb#22]
Hi,
I am curious about why ncounts in h5ads are different than both read count and UMI count.
Thank you very much in advance!

**Comment by tessadgreen** [comment]
ncounts should be the output of 'total_counts' from the scanpy function `sc.pp.calculate_qc_metrics`. 

There was at least one case where ncounts was supplied by the authors and we used their value, though (see [CuiHacohen2023](https://github.com/sanderlab/scPerturb/blob/master/dataset_processing/notebooks/CuiHacohen2023.ipynb)), and it's possible that there was a discrepancy there due to filtering. If you have a specific dataset that isn't performing well we can look into it. 

The dataset processing files are [here](https://github.com/sanderlab/scPerturb/tree/master/dataset_processing/scripts), check those out to see how ncounts was computed.
